# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bitway-db
    environment:
      POSTGRES_DB: bitway
      POSTGRES_USER: bitway_user
      POSTGRES_PASSWORD: bitway_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitway-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: db
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DB: bitway
      SPRING_DATASOURCE_USERNAME: bitway_user
      SPRING_DATASOURCE_PASSWORD: bitway_pass
    depends_on:
      - db

volumes:
  pgdata: