version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bitway_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bitway123
      POSTGRES_DB: bitway_local
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bitway-net

  redis:
    image: redis:7
    container_name: bitway_redis
    ports:
      - "6379:6379"
    networks:
      - bitway-net

volumes:
  pgdata:

networks:
  bitway-net:
